# Generated by Django 5.0.2 on 2024-03-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='ower',
            new_name='owner',
        ),
    ]
